name: gh-pages build

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ⏬
              uses: actions/checkout@v2

            - name: Install 🔧
              run: cd website && npm install

            - name: Build 🔥
              run: cd website && CI='' npm run build

            - name: Relocation 🚚
              run: mkdir -p ./out/show-passwords && mv ./website/dist/* ./out/show-passwords

            - name: Setup Pages ⚙
              uses: actions/configure-pages@v3

            - name: Upload artifact 🔼
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./out"

            - name: Deploy to GitHub Pages 🚀
              id: deployment
              uses: actions/deploy-pages@v4
